# Generated by Django 4.1.5 on 2023-02-02 03:38

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blog_title", models.CharField(max_length=255)),
                ("blog_subtitle", models.CharField(default="", max_length=255)),
                ("blog_tags", models.CharField(max_length=255)),
                ("blog_slug", models.SlugField(default="", unique=True)),
                ("blog_article", tinymce.models.HTMLField(blank=True)),
                ("blog_description", models.CharField(default="", max_length=175)),
                (
                    "blog_image",
                    models.ImageField(default="", upload_to="photos/%Y/%m/%d/"),
                ),
                (
                    "blog_card_image",
                    models.ImageField(default="", upload_to="photos/%Y/%m/%d/"),
                ),
                (
                    "blog_date_posted",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                ("blog_article_active", models.BooleanField(default=False)),
                ("blog_author", models.CharField(max_length=150)),
            ],
        ),
    ]
